## NumPy'e giriş ve neden NumPy ?

<span style='color:blue'>HATIRLATMA</span>
> <span style='color:orange'>Array(dizi) bilgisayar bilimlerinde dizinle (satır numarasıyla) erişilen bir veri öbeği oluşturmak için kullanılan bir veri yapısıdır. Çoğu programlama dilinde bir dizinin tuttuğu bütün öğeler aynı veri türündendir ve dizi ardışık bellek adresleriyle gösterilen konumlarda saklanır.</span>


* 2005 yılında Amerikalı bir veri bilimci olan **Travis Oliphant**, Numarray'in özelliklerini kapsamlı değişikliklerle Numeric'e dahil ederek NumPy'yi yarattı.

* NumPy dizilerle çalışmak için kullanılan bir python kütüphanesidir.
NumPy adı 'Numerical Python' dan gelmektedir.
Ayrıca lineer cebir ve matrisler alanında çalışmak için fonksiyonlara sahiptir.

**NumPy Array'in temel işlevi, n-boyutlu dizi nesnesi için "ndarray"idir.**

* Python dizilerin amacına hizmet eden listlerimiz var ancak işlenmesi yavaştır.**NumPy geleneksel Python listelerinden 50 kata kadar daha hızlı ve daha verimli veri saklama** işlevi gören bir dizi nesnesi sağlamayı amaçlar.

<span style='color:blue'>-Peki NumPy neden listelerden daha hızlı ?</span>
 > **NumPy dizileri,listelerin aksine bellekte tek bir sürekli yerde depolanır,böylece işlemler bunlara çok verimli bir şekilde erişebilir ve işleyebilir.Oysaki listelerde her bir veri için tek tek type sorgulanır ve her veri için bellek ayrılır.Bunu aşağıdaki örneklerle daha iyi kavrayacağız.**


<span style='color:green'>Ek Bilgi</span>
> Yaygın olarak kullanılan bilgisayarlı görü kitaplığı OpenCV'nin Python bağlamaları , verileri depolamak ve üzerinde çalışmak için NumPy dizilerini kullanır. Birden çok kanala sahip görüntüler basitçe üç boyutlu diziler olarak temsil edildiğinden, indeksleme, dilimleme veya diğer dizilerle maskeleme , bir görüntünün belirli piksellerine erişmenin çok etkili yollarıdır. OpenCV'de görüntüler, çıkarılan özellik noktaları , filtre çekirdekleri ve daha pek çok şey için evrensel veri yapısı olarak NumPy dizisi , programlama iş akışını ve hata ayıklamayı büyük ölçüde basitleştirir .

In [11]:
# NumPy kullanmadan, iki listeyi nasıl çarparız ?

a = [1,2,3,4]
b = [4,8,12,16]
ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
print(ab)

[4, 16, 36, 64]


In [1]:
# NumPy kullanarak , iki listeyi nasıl çarparız ?

import numpy as np

a = np.array([1,2,3,4])
b = np.array([4,8,12,16])

print(a*b)

[ 4 16 36 64]


In [5]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([4,8,12,16])

a*b

array([ 4, 16, 36, 64])

In [14]:
# Özetle optimizasyon anlamında,yazılımsal anlamda ve veri saklama konusunda NumPy, Listlere göre daha kullanışlıdır. 

<span style='color:purple'>NUMPY VERİ TİPLERİ</span> 

> Bir Numpy dizisi homojen olması gerekir.Yani veri tiplerinin aynı olma durumudur.

> Numpy, Python’dan farklı olarak 16 farklı veri tipini destekler. (_bool, int_, intc, intp, int8, int16, int32, int64, uint8, uint16, uint32, uint64, float_, float16, float32, float64, complex_, complex64, complex128)

> “ _  ” ile biten veri tipleri o veri tipinin en yüksek değerinin kısa halidir. Örneğin float_ için float64 değeridir. Ayrıca int8, int16, int32, int64 yerine sırasıyla  ‘i1’, ‘i2′,’i4’ vb. string’leri de kullanılabilir.

## Tam Sayılar

En sık kullanılan tamsayı formları int8, int16, int32, int64'tür.

In [15]:
import numpy as np
a = np.array([3.7, 4, 5, 6.5],dtype="int")
a

array([3, 4, 5, 6])

In [16]:
a.dtype

dtype('int32')

## İşaretsiz Tamsayılar

Eğer veri setinde negatif tamsayı içeren bir veri yoksa bu formatı kullanarak bilgisayardaki belleği daha etkili kullanabiliriz. En sık kullanılan işaretsiz tamsayı formları uint8, uint16, uint32, uint64.

## Mantıksal İfadeler

Eğer veri setinde True veya False gibi ifadeler var ise bu formatı kullanmak oldukça etkilidir.

In [17]:
import warnings
warnings.filterwarnings('ignore')         #Pythondan kaynaklı hataları engellemek için.

data = np.array([0,-5,False,6], dtype=np.bool)
data

array([False,  True, False,  True])

## Ondalıklı Sayılar

In [18]:
b = np.array([3, 4, 5, 6.5],dtype=np.float)
b

array([3. , 4. , 5. , 6.5])

## Karmaşık Sayılar

In [19]:
a = np.array([1+2j, 3+4j, 5+6j])
a.imag

array([2., 4., 6.])

In [20]:
a.real

array([1., 3., 5.])

In [19]:
import numpy as np
b = np.array([3, 4, 5, 6.5],dtype="f")
b

array([3. , 4. , 5. , 6.5], dtype=float32)