## NumPy Array Özellikleri

* ndim (rank)
* shape
* size
* dtype
* eye

In [92]:
import numpy as np

a = np.random.randint(8,size=5)
a

array([2, 1, 7, 2, 4])

In [115]:
import numpy as np

b = np.random.randint(8,size=5)
b.ndim                                          #numpy array nesnesinin boyut sayısını döndürür.

1

In [139]:
import numpy as np

c = np.random.randint(2,11,(3,4))

print(c,",\t",c.ndim)                           #ndim = numpy array nesnesi bir boyutlu dizi ise ndim metodu 1 sonucunu, eğer iki boyutlu array ise 2 sonucunu verir.

[[ 9 10  8  9]
 [ 7  4 10  7]
 [ 7  2  4  4]] ,	 2


In [20]:
import numpy as np

d = np.random.randint(8,11,(3,4))

e = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

f = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

g = np.random.randint(8,11,size=8)    


#size = listenin içindeki toplam eleman sayısının ne kadar olacağını söyler.
#shape = numpy array nesnesinin boyut bilgisi verir.

print(d.shape)
print(e.shape)
print(e.size)
print(f.size)
print(f.shape)
print(g.shape)

(3, 4)
(1, 10)
10
10
(10,)
(8,)


In [21]:
import numpy as np

m = np.random.randint(8,size=5)
m.dtype                                                   #numpy array nesnesinin tipini döndürür.

dtype('int32')

In [22]:
import numpy as np

np.eye(6,dtype="int")                                                       #numpy.eye() → Belirlenen boyutlarda 'birim matris' oluşturmamızı sağlayan fonksiyon.

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

## NumPy Array'i Oluşturmak

<span style='color:blue'>NumPy Array, tıpkı Pythondaki list,tuple,dict gibi bir veri tipidir diyebiliriz.</span>

In [10]:
import numpy as np

a = np.array([1,2,3,4,5])   #tek boyutlu bir array

print("output:",a,"\n")
print("output:",a.dtype,"\n")
print("output:",type(a))

output: [1 2 3 4 5] 

output: int32 

output: <class 'numpy.ndarray'>


**ÖNEMLİ**  
* Eğer bir Numpy dizisine farklı veri tiplerinden değerler girersek dizi içerisinde belli bir kurala bağlı veri dönüşümleri meydana gelir. Bu kuralda veri tiplerinin üstünlüğünü şu şekilde sıralayabiliriz:

**String > Float > İnteger > Boolean**


In [11]:
#aşağıdaki kodlarda farklı tipteki veriler içeren bir arrayde , array'in verileri sabit bir türde tuttuğunu görmüş oluyoruz.

import numpy as np

c = np.array([1, 2, 5, 'a'])
c
                                            #listede float bir değer var diğerleri ise int. NumPy Arrayin özelliği NumPy Array listesinin 'SABİT TİP'deki listeyi saklamak.
                                            # işlem sonucunda numpy arrayin tek bir veri türü olur.Örneğe bakılacak olursa dtype = 'dtype = <u11'

array(['1', '2', '5', 'a'], dtype='<U11')

In [21]:
import numpy as np

d = np.array([1, 2.2, 5, 'a'])
d
                       

array(['1', '2.2', '5', 'a'], dtype='<U32')

In [22]:
import numpy as np

e = np.array([1.5, 2.2, 5.8, 'a'])
e
                        

array(['1.5', '2.2', '5.8', 'a'], dtype='<U32')

In [2]:
import numpy as np

k = np.array([7.5, 2, 5.78, 7],dtype="float")
k

array([7.5 , 2.  , 5.78, 7.  ])

In [36]:
import numpy as np

l = np.array([1.5, 2, 5, 7],dtype="int")
l[0]

1

In [12]:
import numpy as np

#e = np.array([1.5, 2.2, 5.8, 'a'],dtype="int")

# hata verir. Çünkü dtype'ı int diye tanımladık ama dizinin içinde 'a' karakteri var.

<span style='color:purple'>**SIFIRDAN ARRAY OLUŞTURMA**</span>

## np.zeros()

In [1]:
import numpy as np

np.zeros(4,dtype="int")                 

array([0, 0, 0, 0])

In [51]:
import numpy as np
   
np.zeros((3,4),dtype="int")                #Tüm elemanları 0 olan 3'e 4 lük bir matrix(çift boyutlu) array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## np.ones()

In [180]:
import numpy as np

np.ones((3,2),dtype="int")                #Tüm elemanları 1 olan 3'e 2 lük bir matrix(çift boyutlu) array

array([[1, 1],
       [1, 1],
       [1, 1]])

## np.full()

In [161]:
import numpy as np

np.full((5,2),9)                          # numpy.full() : istediğimiz sayıyı n boyutlu arraye çeviren bir numpy metodudur.

                                          #Tüm elemanları 9 olan 5'e 2 lik bir array
                                          #iki boyutlu dizi oluşturmak isterken aralık belirteriz. !! Unutulmaması gereken şey iki boyutlu olmaası için parametreler 1 den başlar. 
                                          #0 olursa hata verir ---> (0,0) , (5,0)  # sütun boş bırakılırsa tek boyutlu array olur ---> (1,) (1,5) (8,) böyle olursa tek boyutlu olur.

array([[9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9]])

## np.empty()

In [13]:
np.empty((2,2))                         # numpy.empty() işlevi, girişleri başlatmadan, verilen şekil ve türde yeni bir dizi oluşturmak için kullanılır.

array([[1.08561805e-311, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

## np.arange()

In [25]:
import numpy as np

np.arange(10,30,3)                         #np.arange(başlangıç,bitiş,adım sayısı)

array([10, 13, 16, 19, 22, 25, 28])

## np.linspace()

In [14]:
import numpy as np
                                           #(1.değeri,2.değer,kaç tane değer olacak)
np.linspace(3,16,10)                      #Belirtilen değerler arasında eşit aralıklı sayılar döndürür.
                            #mesela bu yandaki örnekte her değer arasında fark yaklaşık 1,4 değeridir.

array([ 3.        ,  4.44444444,  5.88888889,  7.33333333,  8.77777778,
       10.22222222, 11.66666667, 13.11111111, 14.55555556, 16.        ])

## np.random.rand()

In [17]:
import numpy as np

print(np.random.rand(),"\n")   #numpy.rand()yöntemi, 0 ile 1 arasında rastgele bir kayan nokta döndürür.

np.random.rand(3)

0.2987890195837052 



array([0.1529859 , 0.09354303, 0.22610147])

## np.random.randn()

In [18]:
import numpy as np

x = np.random.randn(5)                      #numpy.rand()yöntemi, -1 ile 1 arasında rastgele bir kayan nokta döndürür.
x

array([ 0.41749669, -1.04336849, -1.6347529 ,  0.53356245,  0.2150251 ])

## np.random.choice()

In [19]:
from numpy import random

x = random.choice([3, 5, 7, 9])       #Bir dizideki değerlerden birini döndürür.
x

7

In [34]:
import numpy as np
x = np.random.choice([3, 5, 7, 9], size=(3, 5))   #Dizi parametresindeki (3, 5, 7 ve 9) değerlerden oluşan 2 boyutlu bir dizi oluşturur.
x

array([[3, 9, 7, 7, 7],
       [5, 5, 9, 5, 5],
       [5, 3, 9, 5, 9]])

## np.random.normal()

In [10]:
import numpy as np

a = np.random.normal(5,3,(3,4)) #ortalaması 5 standart sapması 3 olan 2x2'lik rastgele elemanlardan oluşan bir matrix (ortalama , standart sapma , boyut) = (loc,scale)
print("a matrisi: ",a,"\n\n","a matrisinin standart sapma değeri: ",np.std(a))

a matrisi:  [[ 9.31805644  2.09378034  3.12010768  5.03694985]
 [ 3.02301179  6.06580984  4.17899542  5.92782907]
 [ 3.29729272  7.27019216  4.39578108 10.76786824]] 

 a matrisinin standart sapma değeri:  2.536542009755181


In [11]:
a = np.random.normal(20,6,8)   #ortalaması 20 standart sapması 6 olan 8 rastgele elemandan oluşan bir boyutlu array
a

array([12.05062927, 20.26768176, 20.32140382, 17.0688746 , 25.74129133,
       24.85032236, 18.08651008, 17.22216579])

## np.random.randint()

In [199]:
import numpy as np

np.random.randint(7,22,(4,6))              #iki sayı arasında rastgele tam sayılar üreten 4'e 6 lık bir matrix

array([[ 8, 21,  8, 21,  9, 20],
       [21, 21, 20, 13, 13, 19],
       [14, 20,  8, 18, 19, 21],
       [14, 15, 21, 16, 13, 16]])

! **tek boyutlu arrayin karşılığı vektör , çift boyutlu arrayin karşılığı matrixdir.**