## NumPy Array Özellikleri

* ndim (rank)
* shape
* size
* dtype
* eye

In [ ]:
import numpy as np

a = np.random.randint(8,size=5)
a

array([0, 6, 0, 5, 7])

In [2]:
import numpy as np

b = np.random.randint(8,11,size=5)
b.ndim                                          

                                                #ndim = numpy array nesnesi bir boyutlu dizi ise ndim metodu 1 sonucunu, eğer iki boyutlu array ise 2 sonucunu verir.
                                                # eğer tek boyut için rastgele sayı üretmesini istiyorsak 1 sayı girip max oraya kadar rastgele sayı üretebilir.Yani illa 2 sayı girmemize gerek kalmaz.
                                                #numpy array nesnesinin boyut sayısını(1/2) döndürür.

1

In [52]:
import numpy as np

c = np.random.randint(2,11,(3,3))

print(c,",\t",c.ndim)                           #ndim = numpy array nesnesi bir boyutlu dizi ise ndim metodu 1 sonucunu, eğer iki boyutlu array ise 2 sonucunu verir.
                                                # eğer tek boyut için rastgele sayı üretmesini istiyorsak 1 sayı girip max oraya kadar rastgele sayı üretebilir.Yani illa 2 sayı girmemize gerek kalmaz.

[[ 6  9  8]
 [ 5 10  8]
 [ 3  3  7]] ,	 2


In [53]:
import numpy as np

b = np.random.randint(8,size= (3,5))
b

array([[0, 0, 3, 3, 7],
       [5, 7, 7, 5, 0],
       [6, 6, 3, 4, 4]])

In [54]:
import numpy as np

b = np.random.randint(8,11,size = (3,5))    # randint metodunda 2 sayı arasında rastgele sayı oluşturulduğu gibi tek sayı yazarak da mx o sayıya kadar rastgele
                                   # sayılar oluşturabiliriz. Fakat 2 boyutlu arrayler için oluşturacaksak size = (a,b) şeklinde belirtmemiz lazım.
                                   # sadece arrayi belirtip size'ı yazmazsak hata verir.
b

array([[ 9,  8,  9,  8,  9],
       [ 8,  9, 10,  9,  8],
       [ 8, 10, 10,  9,  9]])

In [ ]:
import numpy as np

b = np.random.randint(8,(3,5))  # hata verecektir.Çünkü kullanıma uygun değil.
b

ValueError: low >= high

In [56]:
import numpy as np


d = np.random.randint(8,11,size=(3,4))

e = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

f = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

g = np.random.randint(8,11,size=(5,2))  

h = np.array([[1,2,3],[4,5,6]])


#size = listenin içindeki toplam eleman sayısının ne kadar olacağını söyler.
#shape = numpy array nesnesinin boyut bilgisi verir.

print(d,"\n")
print(d.shape)
print("\n")
print(e)
print(e.shape)
print(e.size)
print("\n")
print(f.size)
print(f.shape)
print("\n")
print(g)
print(g.size)
print(g.shape)
print("\n")
print(h.shape)
print(h)

[[ 9  9  8  8]
 [ 9  9  8  8]
 [ 8  9  9 10]] 

(3, 4)


[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)
10


10
(10,)


[[ 8  9]
 [ 9  8]
 [ 8  8]
 [10  9]
 [10  8]]
10
(5, 2)


(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

m = np.random.randint(8,size=5)
m.dtype                                                   #numpy array nesnesinin tipini döndürür.

array([2, 3, 5, 0, 3])

In [6]:
import numpy as np

np.eye(6,dtype="int")                                                       #numpy.eye() → Belirlenen boyutlarda 'birim matris' oluşturmamızı sağlayan fonksiyon.

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

## NumPy Array'i Oluşturmak

<span style='color:blue'>NumPy Array, tıpkı Pythondaki list,tuple,dict gibi bir veri tipidir diyebiliriz.</span>

In [7]:
import numpy as np

a = np.array([1,2,3,4,5])   #tek boyutlu bir array

print("output:",a,"\n")
print("output:",a.dtype,"\n")
print("output:",type(a))

output: [1 2 3 4 5] 

output: int32 

output: <class 'numpy.ndarray'>


**ÖNEMLİ**  
* Eğer bir Numpy dizisine farklı veri tiplerinden değerler girersek dizi içerisinde belli bir kurala bağlı veri dönüşümleri meydana gelir. Bu kuralda veri tiplerinin üstünlüğünü şu şekilde sıralayabiliriz:

**String > Float > İnteger > Boolean**


In [8]:
#aşağıdaki kodlarda farklı tipteki veriler içeren bir arrayde , array'in verileri sabit bir türde tuttuğunu görmüş oluyoruz.

import numpy as np

c = np.array([1, 2, 5, 'a'])
c
                                            #listede float bir değer var diğerleri ise int. NumPy Arrayin özelliği NumPy Array listesinin 'SABİT TİP'deki listeyi saklamak.
                                            # işlem sonucunda numpy arrayin tek bir veri türü olur.Örneğe bakılacak olursa dtype = 'dtype = <u11'

array(['1', '2', '5', 'a'], dtype='<U11')

In [9]:
import numpy as np

d = np.array([1, 2.2, 5, 'a'])
d
                       

array(['1', '2.2', '5', 'a'], dtype='<U32')

In [10]:
import numpy as np

e = np.array([1.5, 2.2, 5.8, 'a'])
e
                        

array(['1.5', '2.2', '5.8', 'a'], dtype='<U32')

In [11]:
import numpy as np

k = np.array([7.5, 2, 5.78, 7],dtype="float")
k

array([7.5 , 2.  , 5.78, 7.  ])

In [12]:
import numpy as np

l = np.array([1.5, 2, 5, 7],dtype="int")
l[0]

1

In [13]:
import numpy as np

#e = np.array([1.5, 2.2, 5.8, 'a'],dtype="int")

# hata verir. Çünkü dtype'ı int diye tanımladık ama dizinin içinde 'a' karakteri var.

<span style='color:purple'>**SIFIRDAN ARRAY OLUŞTURMA**</span>

## np.zeros()

In [58]:
import numpy as np

np.zeros(4,dtype="int")                 

array([0, 0, 0, 0])

In [15]:
import numpy as np
   
np.zeros((3,4),dtype="int")                #Tüm elemanları 0 olan 3'e 4 lük bir matrix(çift boyutlu) array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## np.ones()

In [179]:
import numpy as np

np.ones((3,2),dtype="int")                #Tüm elemanları 1 olan 3'e 2 lük bir matrix(çift boyutlu) array

array([[1, 1],
       [1, 1],
       [1, 1]])

## np.full()

In [75]:
import numpy as np

np.full((5,2),9)                          # numpy.full() : istediğimiz sayıyı n boyutlu arraye çeviren bir numpy metodudur.

                                          #Tüm elemanları 9 olan 5'e 2 lik bir array
                                          #iki boyutlu dizi oluşturmak isterken aralık belirteriz. !! Unutulmaması gereken şey iki boyutlu olmaası için parametreler 1 den başlar. 
                                          #0 olursa hata verir ---> (0,0) , (5,0)  # sütun boş bırakılırsa tek boyutlu array olur ---> (1,) (1,5) (8,) böyle olursa tek boyutlu olur.

array([[9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9]])

## np.empty()

In [180]:
np.empty((2,2))                         # numpy.empty() işlevi, girişleri başlatmadan, verilen şekil ve türde yeni bir dizi oluşturmak için kullanılır.

array([[1.        , 2.33333333],
       [3.66666667, 5.        ]])

## np.arange()

In [119]:
#np.arange(başlangıç,bitiş,adım sayısı)

import numpy as np

print(np.arange(2,16,1))
print(np.arange(10,30.5,2.5))
np.arange(5.5,15.5,3)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[10.  12.5 15.  17.5 20.  22.5 25.  27.5 30. ]


array([ 5.5,  8.5, 11.5, 14.5])

## np.linspace()

In [59]:
import numpy as np

print(np.linspace(1,5,8))
print(np.linspace(-2,11,10))
                                           #(1.değeri,2.değer,kaç tane değer olacak)
    
np.linspace(7.5,35.5,5)                          #Belirtilen değerler arasında eşit aralıklı sayılar döndürür.
                                                 #mesela bu yandaki örnekte her değer arasında fark 7 dir.

[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]
[-2.         -0.55555556  0.88888889  2.33333333  3.77777778  5.22222222
  6.66666667  8.11111111  9.55555556 11.        ]


array([ 7.5, 14.5, 21.5, 28.5, 35.5])

## np.random.rand()

In [21]:
import numpy as np

print(np.random.rand(),"\n")   #numpy.rand()yöntemi, 0 ile 1 arasında rastgele bir kayan nokta döndürür.Python random modülündeki random.random()
                               # metodundan farklı olarak; np.random.rand(a) 'da 0 ve 1 arasında a tane sayı gelmesini sağlayabiliriz. random.random()
                               # metodunda böyle bir parametre giremeyiz.

np.random.rand(3)

0.6756161968003667 



array([0.38855791, 0.65964693, 0.35842278])

## np.random.randn()

In [22]:
import numpy as np

x = np.random.randn(5)                      #numpy.rand()yöntemi, -1 ile 1 arasında rastgele bir kayan nokta döndürür.
x

array([ 1.7362573 , -0.00233288,  1.14604169,  0.06706319, -0.91245544])

## np.random.uniform()

In [161]:
# 2 sayı arasında rastgele ondalıklı sayı üretir.
import numpy as np
np.random.uniform(5,25,(2,4))

array([[ 8.47634674,  5.31582812, 18.7558491 , 14.33294999],
       [20.43252117, 15.04627601, 22.27108755, 18.4883635 ]])

## np.random.choice()

In [153]:
from numpy import random

x = random.choice([3, 5, 7, 9])       #Bir dizideki değerlerden birini döndürür.
x

3

In [182]:
import numpy as np
x = np.random.choice([3, 5, 7, 9], size=(3, 5))   #Dizi parametresindeki (3, 5, 7 ve 9) değerlerden oluşan 2 boyutlu bir dizi oluşturur.
x

array([[5, 3, 3, 5, 5],
       [5, 5, 5, 7, 7],
       [3, 5, 3, 5, 9]])

## np.random.normal()

In [172]:
#random.normal(loc=0.0, scale=1.0, size=None)
import numpy as np

a = np.random.normal(5,3,(3,4)) #ortalaması 5 standart sapması 3 olan 3x4'lik rastgele elemanlardan oluşan bir matrix (ortalama , standart sapma , boyut) = (loc,scale)
print("a matrisi: ",a,"\n\n","a matrisinin standart sapma değeri: ",np.std(a))

a matrisi:  [[ 5.66236892  5.22534908  6.356563    0.69965006]
 [ 8.11587829  0.42194607  4.87509582 -0.12778871]
 [ 5.89797257  4.75662792  5.53881813  5.33049216]] 

 a matrisinin standart sapma değeri:  2.4948012525500287


In [26]:
a = np.random.normal(20,6,8)   #ortalaması 20 standart sapması 6 olan 8 rastgele elemandan oluşan bir boyutlu array
a

array([25.5263009 , 20.46357273, 12.17752909, 17.31072997, 36.84252905,
       16.5514262 , 26.24425735, 20.29154029])

## np.random.randint()

In [61]:
import numpy as np

np.random.randint(7,22,(4,6))              #iki sayı arasında rastgele tam sayılar üreten 4'e 6 lık bir matrix

array([[18, 16, 21, 19, 13, 10],
       [16,  7, 17, 15, 21, 11],
       [ 9,  8, 19, 17, 19, 12],
       [14, 18, 21, 15, 20, 12]])

! **tek boyutlu arrayin karşılığı vektör , çift boyutlu arrayin karşılığı matrixdir.**