## Yeniden Şekillendirme (reshaping)

In [4]:
import numpy as np

a = np.arange(1,8)
a

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
import numpy as np

b = np.arange(1,9)
b.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
import numpy as np

c = np.arange(5,29,2)
d = c.reshape((4,3))

print(d,"\n\n",c.ndim,"\n\n",d.ndim)

[[ 5  7  9]
 [11 13 15]
 [17 19 21]
 [23 25 27]] 

 1 

 2


In [7]:
e = np.random.randint(1,9,(2,4)).reshape((4,2))
f = np.random.randint(1,70,size=40).reshape((10,4))

print(e,"\n\n\n",f)

[[6 7]
 [1 3]
 [6 5]
 [7 7]] 


 [[67 22 36 46]
 [ 6 10 40 48]
 [44 50 11 17]
 [57 51 66 46]
 [ 3  5 39 35]
 [66 61 32 10]
 [34 25 17  8]
 [15 63 18 57]
 [45 11 68 49]
 [22 36 51 31]]


In [8]:
from numpy import *

a = arange(20).reshape((5,4))

print(a,"\n")

print("\n",a.sum(axis=0),"\n")   #arrayin sütunları([1.sütundaki değerler top.,2.sütun,.......,n.sütun]) toplamı

a.sum(axis=1)               #arrayin satırları([1.satırdaki değerler top.,2.satır,.....,n.satır]) toplamı

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 


 [40 45 50 55] 



array([ 6, 22, 38, 54, 70])

In [16]:
# Basitçe söylemek gerekirse, bir kez numpy.newaxis kullanıldığında mevcut dizinin boyutunu bir boyut daha artırmak için kullanılır

# 1D array will become 2D array
# 2D array will become 3D array
# 3D array will become 4D array
# 4D array will become 5D array

import numpy as np

a = np.arange(1,8)

print(a,"\n")

print(a[np.newaxis,:],"\n")

a[:,np.newaxis]

[1 2 3 4 5 6 7] 

[[1 2 3 4 5 6 7]] 



array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

## Array Birleştirme (Concatenation)

In [3]:
# tek boyutlu arrayler kendi arasında, iki boyutlu arrayler kendi arasında toplanır.
#
import numpy as np

x = np.array([1,2,3])
y = np.array([4,5])

print(np.concatenate([x,y]))

[1 2 3 4 5]


In [95]:
import numpy as np

a = np.array([[1,2,3],
             [4,5,6]])

b = np.array([[7,8,9],
             [10,11,12]])

print(np.concatenate([a,b]),"\n\n",np.concatenate([a,b],axis=0),"\n\n",np.concatenate([a,b],axis=1))

#iki boyutlu bir diziyle diğer iki boyutlu dizinin aynı satırları yanyana gelmesini istiyorsak axis=1 istemiyorsak axis=0 olmalı. 


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [2]:
import numpy as np

a = np.array([[1,2,3],
             [4,5,6]])

b = np.array([[7,8,9],
             [10,11,12],
             [13,14,15]])

print(np.concatenate([a,b],axis=0))

# iki boyutlu arraylerde axis=0 olduğunda "sütun sayıları eşit olmak şartıyla" farklı boyutta arrayler de toplanabilirken, 
# iki boyutlu arraylerde axis=1 olduğunda "satur sayıları eşit olmak şartıyla" farklı boyutta arrayler de toplanabilir. 

# iki durum da aksi durum yaşanırsa hata verir.


# print(np.concatenate([a,b],axis=1)) ---> ValueError

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


## Array Ayırma (splitting)

In [27]:
# TEK BOYUTLU AYIRMA

import numpy as np

a = np.array([1,2,3,10,11,12,50,60,70])

print(np.split(a,3))

print("\n",np.split(a,[3,6]))

[array([1, 2, 3]), array([10, 11, 12]), array([50, 60, 70])]

 [array([1, 2, 3]), array([10, 11, 12]), array([50, 60, 70])]


In [28]:
import numpy as np

a = np.array([1,2,3,10,11,12,50,60,70])
b,c,d = np.split(a,[3,6])

print(b,c,d)

[1 2 3] [10 11 12] [50 60 70]


In [43]:
import numpy as np

a = np.array([70,80,90,100,110,120,130,140,150,150])
np.split(a,5)

[array([70, 80]),
 array([ 90, 100]),
 array([110, 120]),
 array([130, 140]),
 array([150, 150])]

In [6]:
# İKİ BOYUTLU AYIRMA

import numpy as np
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
import numpy as np

a = np.arange(16).reshape(4,4)

print(a,"\n\n")

print(np.split(a,4),"\n\n")

print(np.split(a,2),"\n\n")
print(np.vsplit(a,[2]),"\n\n")         #vsplit() = Bir diziyi dikey olarak (satır bazında) birden çok alt diziye ayırın.
print(np.hsplit(a,[2]),"\n\n")         #hsplit() = Bir diziyi yatay olarak (sütun bazında) birden çok alt diziye ayırın. 

print("\nsol: ",np.hsplit(a,[2])[0],"\n\n\nsağ: ",np.hsplit(a,[2])[1])       

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])] 


[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])] 


[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])] 


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])] 



sol:  [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 


sağ:  [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Dizi Arama

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)                             #numpy.where () işlevi, verilen koşulun karşılandığı bir giriş dizisindeki öğelerin indekslerini döndürür.
x

(array([1, 3, 5, 7], dtype=int64),)

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)
x

(array([0, 2, 4, 6], dtype=int64),)

In [213]:
import numpy as np

arr = np.array([1, 2, 3, 5, 5, 4, 5, 6, 5, 7, 8])

x = np.where(arr == 5)

x

(array([3, 4, 6, 8], dtype=int64),)

## Sıralama (Sorting)

In [ ]:
import numpy as np

x = np.array([4,1,9,8,2])
np.sort(x)                   # np.sort NumPy içerisinden çağrıldığı için veri setinin yapısını tamamen değiştirmedi.

array([1, 2, 4, 8, 9])

In [ ]:
x

array([1, 2, 4, 8, 9])

In [31]:
import numpy as np

x = np.array([4,1,9,8,2])
x.sort()                     #  liste yöntemlerinden biri olan bu sort yapısı ise veri setinin yapısını değiştirdi.
x

array([1, 2, 4, 8, 9])

In [32]:
x

array([1, 2, 4, 8, 9])

In [48]:
import numpy as np

d = np.random.normal(20,5,(3,3))
np.sort(d,axis = 0)                # sütunlara göre küçükten büyüğe sıralama

array([[20.99444347, 17.30004304, 17.03946856],
       [24.23605994, 17.73491088, 18.84043841],
       [24.7773086 , 20.39368873, 36.98131315]])

In [54]:
import numpy as np

d = np.random.normal(20,5,(3,3))
np.sort(d,axis = 1)               # satırlara göre küçükten büyüğe sıralama

array([[17.89196031, 25.71111701, 28.57845768],
       [17.12466076, 19.35523079, 23.27456366],
       [14.73329239, 19.44400316, 21.43725827]])

In [37]:
# Quizdeki soru

import numpy as np

5*np.array([2, 1, 4, 3, 5])


array([10,  5, 20, 15, 25])

In [ ]:
# axislerde olay şu: eğer birleştirme, ayırma gibi durumlar varsa bildiğin yöntem gibi yap(0 dediğinde aşağı baz al, 1 dediğinde yanları)
#eğer arraylerdeki veriler için sıralama,toplama vb. şeyler varsa bildiğin yöntemin tam tersi.

In [ ]:
# QUİZ - kümülatif
import numpy as np
arr = np.array([1,2,3])
print(np.cumsum(arr))

[1 3 6]
