## İndex İle Elemanlara Erişmek

In [16]:
import numpy as np

a = np.random.randint(10,size=10)

print(a,",",a[5],",",a[-1])

a[0]=3
print(a)

[8 3 1 7 1 9 1 5 7 5] , 9 , 5
[3 3 1 7 1 9 1 5 7 5]


In [17]:
a

array([3, 3, 1, 7, 1, 9, 1, 5, 7, 5])

In [6]:
import numpy as np

b = np.random.randint(8,size= (3,5))
b

array([[4, 7, 2, 1, 3],
       [3, 3, 6, 3, 0],
       [1, 5, 5, 4, 4]])

In [8]:
import numpy as np

b = np.random.randint(8,size= (3,5))

print(b,",",b[0,2],",",b[1,4])       # iki boyutlu arraylerde elemanlara erişmek için [satır,sütun]

b[1,4] = 9
b[2,1] = 5.5                         # array'e float bir sayı eklemek istedik kabul etmedi int li halini aldı.Çünkü NumPy Array'in prensibi bu. 

print("\n",b)

[[3 7 0 5 1]
 [7 7 5 2 3]
 [3 3 3 0 7]] , 0 , 3

 [[3 7 0 5 1]
 [7 7 5 2 9]
 [3 5 3 0 7]]


## Array Alt Küme İşlemleri (Slicing)

In [2]:
import numpy as np
a = np.arange(20,30)

print(a,"\n")
print(a[0:3],"\n")
print(a[:3],"\n")
print(a[2:],"\n")
print(a[:],"\n")
print(a[0::3],"\n")
print(a[::-1])

[20 21 22 23 24 25 26 27 28 29] 

[20 21 22] 

[20 21 22] 

[22 23 24 25 26 27 28 29] 

[20 21 22 23 24 25 26 27 28 29] 

[20 23 26 29] 

[29 28 27 26 25 24 23 22 21 20]


In [4]:
import numpy as np

b = np.random.randint(10,size= (5,5))

print(b,"\n\n")                     # iki boyutlu arraylerin alt kümelerine ve elemanlarına erişmek için [ , ] yöntemi kullanılır.

print(b[:,3],",",b[:,0])            # iki boyutlu dizinin sütunlarını almak. [:,x] x: integer değer. buradaki olay satırdaki listeleri alıp her bir listenin x.sütunundaki değeri almak

print("\n",b[0,:],b[1,:],b[0])      # iki boyutlu dizinin satırlarına ulaşmak için

print("\n",b[::,:2],"\n\n",b[0:3,:2])


[[7 5 0 3 2]
 [3 2 8 9 2]
 [9 0 4 7 8]
 [8 5 7 6 9]
 [4 1 4 0 5]] 


[3 9 7 6 0] , [7 3 9 8 4]

 [7 5 0 3 2] [3 2 8 9 2] [7 5 0 3 2]

 [[7 5]
 [3 2]
 [9 0]
 [8 5]
 [4 1]] 

 [[7 5]
 [3 2]
 [9 0]]


## Alt Küme Üzerinde İşlem Yapmak

In [132]:
import numpy as np

a = np.random.randint(8,size= (4,4))
a

array([[3, 3, 6, 0],
       [3, 4, 5, 3],
       [0, 0, 0, 3],
       [3, 5, 5, 1]])

**Önceki bölümlerde Array alt kümelerinde elemanlarda bazı değişiklikler yaptık.Bu yaptığımız değişiklikler Ana Arrayi de etkiledi yani alt kümelerde yaptığımız değişiklikler sonucunda Ana Array'e değişiklikler de dahil olmuş oldu.Tekrar Arrayı yazdırdığımızda ilk baştaki gibi aynı kalmamış oldu.**
> Peki bunu nasıl engelleriz ? Yani Array'in alt küme üzerinde yaptığımız değişiklikler nasıl Ana arraydan bağımsız bir şekilde gerçekleşebilir ?

* Bu sorunu **copy()** yöntemiyle çözüyoruz.

In [17]:
import numpy as np

a = np.random.randint(8,size= (4,4))

alt_1 = a[0:3,0:2]

print(a,"\n\n",alt_1)

alt_1[0,1] = 999
alt_1[2,0] = 555

print("\n",alt_1)
print("\n",a)   # a arrrayi , alt_1 ile yaptığımız işlemle beraber değişikliğe uğramıştır ve ilk haldeki çıktıyı vermez.Bunu engellemek için alt_1 ile yapacağımız işlemi copy() yöntemini kulllanrak yapıyoruz.

[[1 7 3 6]
 [5 0 2 1]
 [3 0 3 6]
 [6 2 5 6]] 

 [[1 7]
 [5 0]
 [3 0]]

 [[  1 999]
 [  5   0]
 [555   0]]

 [[  1 999   3   6]
 [  5   0   2   1]
 [555   0   3   6]
 [  6   2   5   6]]


In [130]:
import numpy as np

b = np.random.randint(10,size= (5,5))
print(b)

b_alt = b[:3,:3].copy()
b_alt[0,1] = 777
b_alt[2,1] = 555

print("\n\n",b_alt)
print("\n\n",b)



[[6 4 6 9 7]
 [4 0 2 5 6]
 [0 4 3 9 0]
 [9 0 5 2 1]
 [1 7 5 6 4]]


 [[  6 777   6]
 [  4   0   2]
 [  0 555   3]]


 [[6 4 6 9 7]
 [4 0 2 5 6]
 [0 4 3 9 0]
 [9 0 5 2 1]
 [1 7 5 6 4]]


> Yukarıdaki kodlara bakacak olursak Ana Array , Alt küme işleminden sonra orijinalliğini bozmadı bunun sebebi copy() metodudur.Copy metodunu kullanmasaydık alt küme işleminde yapılan değişiklikler Ana kümeyi de etkileyecekti.

## Fancy Index İle Elemanlara Ulaşmak

In [2]:
# TEK BOYUTLULAR DA FANCY INDEX

# Fancy indexing, bir array ya da DataFrame içine bir indis listesi konularak o listedeki indislerin seçilmesidir.

import numpy as np

a = np.arange(10,30,3)
elemanı_al = [0,2,6]

print(a,",",a[elemanı_al])  # bunu [a[0],a[2],a[6]] ile de yapabilirdin ama verisayısı fazla ve birçok veri almak isteseydin 'Fancy Index' yöntemi daha pratik olurdu. 

[10 13 16 19 22 25 28] , [10 16 28]


In [12]:
# İKİ BOYUTLULARDA FANCY INDEX

In [13]:
import numpy as np

a = np.arange(9).reshape((3,3))

satirolsun = np.array([0,1])
sutunolsun = np.array([1,2])
,
print(a,"\n\n\n","fancy Index: ",a[satirolsun,sutunolsun])

[[0 1 2]
 [3 4 5]
 [6 7 8]] 


 fancy Index:  [1 5]


In [14]:
import numpy as np

a = np.arange(15).reshape((5,3))
print(a,"\n\n", "fancy Index: ",a[2, [0,1]])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

 fancy Index:  [6 7]
