## Numpy Array'de Ekleme/Silme İşlemleri

In [3]:
# Tek boyutlu arrraylerde ekleme işlemi

import numpy as np

a = np.array([1,2,3,4,5,6])
np.append(a,8)

array([1, 2, 3, 4, 5, 6, 8])

In [2]:
a

array([1, 2, 3, 4, 5, 6])

In [4]:
b = [1,2,3,4,5,6]
b.append(9)
b

[1, 2, 3, 4, 5, 6, 9]

In [5]:
b

[1, 2, 3, 4, 5, 6, 9]

In [ ]:
"""
Önceki uygulamalarda da burada da görüldüğü üzere python nesnesi gibi davranışlar sergileyen kod blokları sonucu ana veri sonraki satırlarda değişikliğe uğrarken,
numpy içerisinde yer alan metod ana veriyi sadece o satır için değiştirmiş olur. Sonraki satırlarda ana veri korunur.örneğin np.sort ile veri sıralanırken ana dizi korunur.
list.sort ile veri sıralanır fakat ana dizi böylelikle değişmiş olur.
"""

In [78]:
np.insert(a,3,999)

array([  1,   2,   3, 999,   4,   5,   6])

In [3]:
# iki boyutlu arraylerde ekleme işlemi

import numpy as np

b = np.random.randint(2,20,(3,3))
c = np.array([[1,2,3]])

print(b,"\n")
np.append(b,c,0)          #satır bazında

[[12  7  3]
 [ 5 15  2]
 [14 15 15]] 



array([[12,  7,  3],
       [ 5, 15,  2],
       [14, 15, 15],
       [ 1,  2,  3]])

In [92]:
d = np.array([[1],[2],[3]])
np.append(b,d,1)         #sütun bazında

array([[10,  9, 13,  1],
       [ 2,  3,  3,  2],
       [ 4,  9,  2,  3]])

In [88]:
# numpy.delete(arr, obj, axis=None) , None = 0 or 1.  axis=0 satır , axis=1 sütun üzerinden işlem yapmamızı sağlıyordu.

# tek boyutlu arrayde silme işlemi
import numpy as np

a = np.array([1,2,3,4,5,6])
np.delete(a,2)

array([1, 2, 4, 5, 6])

In [3]:
# iki boyutlu arrayde silme işlemi
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr,"\n")
np.delete(arr, 1, 0)  #satır üzerinden silme işlemi yaptık.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 



array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [4]:
np.delete(arr,2,1)  # sütun üzerinden silme işlemi yaparak 3.sütunu sildik.

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [23]:
np.delete(arr, np.s_[::2], 1)  #sütun üzerinden silme işlemini yaptık.

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [24]:
np.delete(arr, [1,3,5], None)

array([ 1,  3,  5,  7,  8,  9, 10, 11, 12])