## Koşullu Eleman İşlemleri

In [1]:
import numpy as np
a = np.array([2,3,4,5,6])

print(a<3)
print(a<=3)
print(a>3)
print(a[a<3],",",a[a>3],",",a[a==3],",",a[a!=3])  # fancy yöntemi var.
print(a*2)
print(a/2)
print(a+2)
print(a-5)
print(a%2)
print(a//2)

[ True False False False False]
[ True  True False False False]
[False False  True  True  True]
[2] , [4 5 6] , [3] , [2 4 5 6]
[ 4  6  8 10 12]
[1.  1.5 2.  2.5 3. ]
[4 5 6 7 8]
[-3 -2 -1  0  1]
[0 1 0 1 0]
[1 1 2 2 3]


## Matematiksel İşlemler

In [7]:
import numpy as np

import warnings                      #Python'dan kaynaklı hataları kapatmak için:
warnings.filterwarnings("ignore") 

a = np.array([8,-12,18,20])

print(a+1,"\n")
print(a-1,"\n")
print(a/2,"\n")
print(a%2,"\n")
print(a**2,"\n")

b = np.add(a,12)
c = np.subtract(a,5)
d = np.multiply(a,2)
e = np.divide(a,3)
f = np.power(a,2)
g = np.absolute([a])
h = np.sqrt(a)

print("\n\n")                   # temel işlemler
print(h,"\n")     
print(b,"\n")
print(c,"\n")
print(d,"\n")
print(e,"\n")
print(f,"\n")
print(g,"\n")

print("\n\n",np.sin(np.radians(30)),",",np.sin(3.14),np.cos(60))          #trigonometrik ifadeler normalde radyan cinsinden alıyor.dereceye çevirip sinüs/cosinüsünü almak istersek np.sin(np.radians()) gibi yapabiliriz.

h = np.array([1,2,3])
print("\n",np.log(h),",",np.log2(h),"",np.log10(h))  #logaritmik ifadeler

[  9 -11  19  21] 

[  7 -13  17  19] 

[ 4. -6.  9. 10.] 

[0 0 0 0] 

[ 64 144 324 400] 




[2.82842712        nan 4.24264069 4.47213595] 

[20  0 30 32] 

[  3 -17  13  15] 

[ 16 -24  36  40] 

[ 2.66666667 -4.          6.          6.66666667] 

[ 64 144 324 400] 

[[ 8 12 18 20]] 



 0.49999999999999994 , 0.0015926529164868282 -0.9524129804151563

 [0.         0.69314718 1.09861229] , [0.        1.        1.5849625]  [0.         0.30103    0.47712125]


## İstatistiksel Hesaplamalar

In [3]:
import numpy as np

a= np.array([3,4,5,6])

print("ortalama:",np.mean(a,axis=0))
print("toplam:",np.sum(a))
print("min:",np.min(a),"max:",np.max(a))
print("varyans:",np.var(a))
print("standart sapma:",np.std(a))
print("Pearson çarpıklık katsayısı:",np.corrcoef(a))

ortalama: 4.5
toplam: 18
min: 3 max: 6
varyans: 1.25
standart sapma: 1.118033988749895
Pearson çarpıklık katsayısı: 1.0


##  Numpy İle İki Bilinmeyenli Denklem Çözümü

5*x0 + x1 = 20

x0 + 4*x1 = 14

In [4]:
import numpy as np

a = np.array([[3,7],[5,1]])
b = np.array([25,30])

print(a)

bilinmeyenleri_bul = np.linalg.solve(a,b)
bilinmeyenleri_bul

[[3 7]
 [5 1]]


array([5.78125, 1.09375])

**dışarıdan bir metin dosyasından veri yükleme**

In [1]:
import numpy as np
np.loadtxt("matrix.txt")

array([[1., 2., 3., 4.],
       [5., 6., 8., 9.],
       [7., 8., 5., 4.]])