## NumPy Uygulama

In [16]:
#1 (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.

import numpy as np
np.array([10,15,30,45,60])

array([10, 15, 30, 45, 60])

In [17]:
#2 (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.

np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
#3 (5-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

np.arange(5,100,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [20]:
#4 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
#5 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
#6 (0-100) arasında eşit aralıklı 5 sayı üretin.

np.linspace(0,100,5)                

array([  0.,  25.,  50.,  75., 100.])

In [29]:
#7 (10-30) arasında rastgele 5 tane tamsayı üretin.

np.random.randint(10,30,size=5)

array([21, 11, 14, 15, 14])

In [106]:
#8 [-1 ile 1] arasında 10 adet sayı üretin.

np.random.randn(10)

array([-0.24101652,  0.94954318, -1.03078894,  0.29677453, -0.96273809,
        0.29882262, -0.09326098, -0.11114609,  1.16862265, -0.18364856])

In [125]:
#9 (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

ö = np.random.randint(10,50,(3,5))
ö

array([[20, 19, 14, 40, 30],
       [12, 45, 13, 24, 13],
       [44, 45, 39, 49, 23]])

In [126]:
#10 üretilen matrisin satır ve sütun sayılarının toplamlarını hesapalayınız.

print(np.sum(ö,axis=0),np.sum(ö,axis=1))     #axis:0 sütunlarının toplamı axis.1 satırların toplamı

[ 76 109  66 113  66] [123 107 200]


In [127]:
#11 üretilen matrisin en büyük, en küçük değeri ve ortalaması nedir ?

print(np.max(ö),np.min(ö),np.mean(ö))

49 12 28.666666666666668


In [136]:
#12 üretilen matrisin en büyük değerinin indeksi kaçtır ?

print(ö,"\n")
print(np.argmax(ö),"\n")    # matrixteki max değerin indeksini döndürür.Yalnız indeksinin döndürürken matrix olmasına rağmen bir vektörmüş gibi bir indeks numarası gelir.
print(np.argmin(ö),"\n")    # matrixteki min değerin indeksini döndürür.  ''

[[20 19 14 40 30]
 [12 45 13 24 13]
 [44 45 39 49 23]] 

13 

5 



In [137]:
#13 (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

a= np.arange(10,20)
a[:3]

array([10, 11, 12])

In [138]:
#14 üretilen dizinin elemanlarını tersten yazdırın.

a[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [140]:
#15 üretilen matrisin ilk satırını seçiniz.

ö[0]

array([20, 19, 14, 40, 30])

In [142]:
#16 üretilen matrisin 2.satır ve 3.sütundaki elemanı hangisidir ?

ö[1,2]

13

In [144]:
#17 üretilen matrisin tüm satırlardaki ilk elemanını seçiniz.

ö[:,0]

array([20, 12, 44])

In [146]:
#18 üretilen matrisin her bir elemanının karesini alınız.

np.power(ö,2)

array([[ 400,  361,  196, 1600,  900],
       [ 144, 2025,  169,  576,  169],
       [1936, 2025, 1521, 2401,  529]], dtype=int32)

In [171]:
#19 üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.

x = np.random.randint(-50,50,(5,5))

print(x,"\n")
x[(x>0) & (x%2==0)]

[[  7  31  44  10  28]
 [ 34  29  -9   5  40]
 [-47  49  36  10  10]
 [  3   6  -1   3  39]
 [ 11  39   3  46  27]] 



array([44, 10, 28, 34, 40, 36, 10, 10,  6, 46])

In [ ]:
#20  np.array([1,2,3,4,5,6]) arrayinde eksen boyunca ögelerin kümülatif toplamı döndürünüz ?

arr = np.array([1,2,3,4,5,6])
print(np.cumsum(arr))

[ 1  3  6 10 15 21]


> **NumPy'de ondalık sayıları yuvarlamak için yöntemler:**
numpy.around() ,
numpy.trunc() ,
numpy.fix()